language: node_js

before_script:
  - npm install

script:
  - npm run build

deploy:
  provider: pages
  skip-cleanup: true
  github-token: $REPO_TOKEN
  keep-history: true
  local-dir: ./dist
  on:
    branch: gh-pages
